version: 2
jobs:
  build:
    docker:
      - image: docker:18.01.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          apk add --no-cache py-pip
          pip install awscli
          eval $(aws ecr get-login --region us-east-1 --no-include-email)
      - run: |
          DOCKER_ARGS="--compress"
          if [ ! -z "${DOCKER_SQUASH}" ] && [[ "$(echo ${DOCKER_SQUASH} | tr '[A-Z]' '[a-z]')" == "true" ]]
          then
            DOCKER_ARGS="${DOCKER_ARGS} --squash"
          fi
          docker build "${DOCKER_ARGS}" -t "${DOCKER_ORG}/circleci-base:${CIRCLE_BRANCH}" -t circleci-base circleci-base/
          docker build "${DOCKER_ARGS}" -t "${DOCKER_ORG}/circleci-fullstack:${CIRCLE_BRANCH}" -t circleci-fullstack circleci-fullstack/
          docker build "${DOCKER_ARGS}" -t "${DOCKER_ORG}/circleci-fullstack-cypress:${CIRCLE_BRANCH}" -t circleci-fullstack-cypress circleci-fullstack-cypress/
          docker build "${DOCKER_ARGS}" -t "${DOCKER_ORG}/circleci-deploy:${CIRCLE_BRANCH}" -t circleci-deploy circleci-deploy/
      - run: |
          docker push "${DOCKER_ORG}/circleci-base:${CIRCLE_BRANCH}"
          docker push "${DOCKER_ORG}/circleci-fullstack:${CIRCLE_BRANCH}"
          docker push "${DOCKER_ORG}/circleci-fullstack-cypress:${CIRCLE_BRANCH}"
          docker push "${DOCKER_ORG}/circleci-deploy:${CIRCLE_BRANCH}"
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
