version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          docker build -t $DOCKER_ORG/circleci-base:$CIRCLE_BRANCH circleci-base/
          docker build -t $DOCKER_ORG/circleci-fullstack:$CIRCLE_BRANCH circleci-fullstack/
          docker build -t $DOCKER_ORG/circleci-fullstack-chrome:$CIRCLE_BRANCH circleci-fullstack-chrome/
      - run: |
          docker push $DOCKER_ORG/circleci-base:$CIRCLE_BRANCH
          docker push $DOCKER_ORG/circleci-fullstack:$CIRCLE_BRANCH
          docker push $DOCKER_ORG/circleci-fullstack-chrome:$CIRCLE_BRANCH

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
